import { Button } from '../components/ui/Button';
import { exportToProfessionalExcel } from '../lib/professionalExcelExport';
import { Download } from 'lucide-react';

/**
 * Test component to demonstrate the enhanced Excel export capabilities
 * This creates a sample report with mock data to showcase all styling features
 */
export function ExcelExportDemo() {
  const generateSampleReport = async () => {
    const mockData = {
      summary: {
        sheetName: 'Summary',
        data: [
          { Field: 'Property Name', Value: 'Grand Vista Hotel' },
          { Field: 'Total Rooms', Value: 150 },
          { Field: 'Report Period', Value: '2024-01-01 to 2024-12-31' },
          { Field: 'Generated By', Value: 'VoyageurNest Analytics' }
        ]
      },
      kpiData: {
        sheetName: 'KPI Dashboard',
        data: [
          { 
            Category: 'Revenue', 
            Metric: 'Total Revenue', 
            Value: 8750000, 
            'Target': 8000000,
            'Variance': 750000,
            'Variance %': 9.4,
            Status: 'Above Target' 
          },
          { 
            Category: 'Revenue', 
            Metric: 'ADR', 
            Value: 4500, 
            'Target': 4200,
            'Variance': 300,
            'Variance %': 7.1,
            Status: 'Above Target' 
          },
          { 
            Category: 'Occupancy', 
            Metric: 'Occupancy Rate', 
            Value: 82.5, 
            'Target': 75,
            'Variance': 7.5,
            'Variance %': 10.0,
            Status: 'Excellent' 
          },
          { 
            Category: 'Occupancy', 
            Metric: 'Room Nights Sold', 
            Value: 45000, 
            'Target': 40000,
            'Variance': 5000,
            'Variance %': 12.5,
            Status: 'Above Target' 
          },
          { 
            Category: 'Guest', 
            Metric: 'Total Bookings', 
            Value: 12500, 
            'Target': 11000,
            'Variance': 1500,
            'Variance %': 13.6,
            Status: 'Excellent' 
          },
          { 
            Category: 'Guest', 
            Metric: 'Repeat Guest Rate', 
            Value: 35.2, 
            'Target': 30,
            'Variance': 5.2,
            'Variance %': 17.3,
            Status: 'Excellent' 
          },
          { 
            Category: 'Performance', 
            Metric: 'Cancellation Rate', 
            Value: 8.5, 
            'Target': 10,
            'Variance': -1.5,
            'Variance %': -15.0,
            Status: 'Good' 
          }
        ],
        columns: ['Category', 'Metric', 'Value', 'Target', 'Variance', 'Variance %', 'Status']
      },
      monthlyData: {
        sheetName: 'Monthly Performance',
        data: [
          { Month: 'January', 'Occupancy Rate': 75.2, Revenue: 650000, 'ADR': 4200, 'Profit': 125000 },
          { Month: 'February', 'Occupancy Rate': 78.5, Revenue: 680000, 'ADR': 4300, 'Profit': 145000 },
          { Month: 'March', 'Occupancy Rate': 82.1, Revenue: 720000, 'ADR': 4400, 'Profit': 165000 },
          { Month: 'April', 'Occupancy Rate': 85.3, Revenue: 750000, 'ADR': 4500, 'Profit': 180000 },
          { Month: 'May', 'Occupancy Rate': 88.7, Revenue: 780000, 'ADR': 4600, 'Profit': 195000 },
          { Month: 'June', 'Occupancy Rate': 91.2, Revenue: 820000, 'ADR': 4700, 'Profit': 215000 },
          { Month: 'July', 'Occupancy Rate': 93.5, Revenue: 850000, 'ADR': 4800, 'Profit': 225000 },
          { Month: 'August', 'Occupancy Rate': 92.8, Revenue: 840000, 'ADR': 4750, 'Profit': 220000 },
          { Month: 'September', 'Occupancy Rate': 87.6, Revenue: 780000, 'ADR': 4600, 'Profit': 190000 },
          { Month: 'October', 'Occupancy Rate': 83.4, Revenue: 730000, 'ADR': 4450, 'Profit': 170000 },
          { Month: 'November', 'Occupancy Rate': 79.8, Revenue: 700000, 'ADR': 4350, 'Profit': 150000 },
          { Month: 'December', 'Occupancy Rate': 76.5, Revenue: 650000, 'ADR': 4250, 'Profit': 130000 }
        ],
        columns: ['Month', 'Occupancy Rate', 'Revenue', 'ADR', 'Profit']
      },
      expenseData: {
        sheetName: 'Expense Analysis',
        data: [
          { Category: 'Salaries & Wages', 'Budgeted Amount': 2500000, 'Actual Amount': 2450000, 'Variance': -50000, 'Variance %': -2.0, Status: 'Under Budget' },
          { Category: 'Utilities', 'Budgeted Amount': 800000, 'Actual Amount': 850000, 'Variance': 50000, 'Variance %': 6.3, Status: 'Over Budget' },
          { Category: 'Maintenance', 'Budgeted Amount': 600000, 'Actual Amount': 580000, 'Variance': -20000, 'Variance %': -3.3, Status: 'Under Budget' },
          { Category: 'Marketing', 'Budgeted Amount': 400000, 'Actual Amount': 420000, 'Variance': 20000, 'Variance %': 5.0, Status: 'Over Budget' },
          { Category: 'Supplies', 'Budgeted Amount': 350000, 'Actual Amount': 340000, 'Variance': -10000, 'Variance %': -2.9, Status: 'Under Budget' },
          { Category: 'Insurance', 'Budgeted Amount': 200000, 'Actual Amount': 200000, 'Variance': 0, 'Variance %': 0.0, Status: 'On Target' },
          { Category: 'Professional Fees', 'Budgeted Amount': 150000, 'Actual Amount': 165000, 'Variance': 15000, 'Variance %': 10.0, Status: 'Over Budget' },
          { Category: 'Technology', 'Budgeted Amount': 250000, 'Actual Amount': 235000, 'Variance': -15000, 'Variance %': -6.0, Status: 'Under Budget' }
        ],
        columns: ['Category', 'Budgeted Amount', 'Actual Amount', 'Variance', 'Variance %', 'Status']
      },
      bookingSources: {
        sheetName: 'Booking Channels',
        data: [
          { Source: 'Direct Website', Bookings: 4500, 'Revenue Share': 35, 'Total Revenue': 3062500, 'Avg ADR': 4800, 'Commission Rate': 0 },
          { Source: 'Booking.com', Bookings: 3200, 'Revenue Share': 25, 'Total Revenue': 2187500, 'Avg ADR': 4300, 'Commission Rate': 15 },
          { Source: 'Expedia', Bookings: 2100, 'Revenue Share': 18, 'Total Revenue': 1575000, 'Avg ADR': 4250, 'Commission Rate': 18 },
          { Source: 'Airbnb', Bookings: 1500, 'Revenue Share': 12, 'Total Revenue': 1050000, 'Avg ADR': 4400, 'Commission Rate': 12 },
          { Source: 'Corporate', Bookings: 800, 'Revenue Share': 7, 'Total Revenue': 612500, 'Avg ADR': 5200, 'Commission Rate': 0 },
          { Source: 'Travel Agents', Bookings: 400, 'Revenue Share': 3, 'Total Revenue': 262500, 'Avg ADR': 4100, 'Commission Rate': 10 }
        ],
        columns: ['Source', 'Bookings', 'Revenue Share', 'Total Revenue', 'Avg ADR', 'Commission Rate']
      },
      guestDemographics: {
        sheetName: 'Guest Origins',
        data: [
          { Country: 'India', Guests: 6500, 'Percentage': 52, 'Avg Stay (nights)': 2.3, 'Avg Spend': 9500 },
          { Country: 'United States', Guests: 1875, 'Percentage': 15, 'Avg Stay (nights)': 3.5, 'Avg Spend': 15000 },
          { Country: 'United Kingdom', Guests: 1250, 'Percentage': 10, 'Avg Stay (nights)': 4.2, 'Avg Spend': 18000 },
          { Country: 'Germany', Guests: 875, 'Percentage': 7, 'Avg Stay (nights)': 3.8, 'Avg Spend': 16500 },
          { Country: 'France', Guests: 750, 'Percentage': 6, 'Avg Stay (nights)': 3.2, 'Avg Spend': 14000 },
          { Country: 'Australia', Guests: 625, 'Percentage': 5, 'Avg Stay (nights)': 5.1, 'Avg Spend': 22000 },
          { Country: 'Others', Guests: 625, 'Percentage': 5, 'Avg Stay (nights)': 3.0, 'Avg Spend': 13000 }
        ],
        columns: ['Country', 'Guests', 'Percentage', 'Avg Stay (nights)', 'Avg Spend']
      }
    };

    // Convert to format expected by export function
    const exportSheets = Object.values(mockData);
    
    const coverData = {
      propertyName: 'Grand Vista Hotel',
      dateRange: { start: '2024-01-01', end: '2024-12-31' },
      reportType: 'Annual Performance Report',
      generatedDate: new Date().toISOString()
    };

    // Generate the Excel file
    await exportToProfessionalExcel(
      exportSheets, 
      'Professional-Excel-Export-Demo.xlsx',
      coverData
    );
  };

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <div className="bg-white rounded-lg shadow-lg p-6">
        <h1 className="text-3xl font-bold text-gray-800 mb-4">
          Excel Export Enhancement Demo
        </h1>
        
        <div className="space-y-4 text-gray-600 mb-8">
          <p>
            This demo showcases the enhanced Excel export capabilities with professional styling,
            conditional formatting, and advanced features.
          </p>
          
          <div className="bg-blue-50 border-l-4 border-blue-500 p-4">
            <h3 className="font-semibold text-blue-800 mb-2">Features Demonstrated:</h3>
            <ul className="list-disc list-inside space-y-1 text-blue-700">
              <li>Professional cover page with branding</li>
              <li>Color-coded KPI dashboard with status indicators</li>
              <li>Automatic currency and percentage formatting</li>
              <li>Conditional formatting for occupancy rates</li>
              <li>Variance analysis with positive/negative coloring</li>
              <li>Budget vs actual comparisons</li>
              <li>Multi-sheet report with navigation icons</li>
              <li>Frozen headers and autofilters</li>
              <li>Print-ready landscape formatting</li>
            </ul>
          </div>
          
          <div className="bg-green-50 border-l-4 border-green-500 p-4">
            <h3 className="font-semibold text-green-800 mb-2">Sample Data Includes:</h3>
            <ul className="list-disc list-inside space-y-1 text-green-700">
              <li>Annual KPI summary with targets and variances</li>
              <li>12-month performance trends</li>
              <li>Expense budget analysis</li>
              <li>Booking channel distribution</li>
              <li>Guest demographics by country</li>
            </ul>
          </div>
        </div>

        <Button 
          onClick={generateSampleReport}
          className="w-full sm:w-auto"
          size="lg"
        >
          <Download className="mr-2 h-5 w-5" />
          Generate Professional Excel Report
        </Button>
        
        <div className="mt-6 p-4 bg-gray-50 rounded-lg">
          <p className="text-sm text-gray-500">
            <strong>Note:</strong> The generated Excel file will open in Microsoft Excel or any compatible
            spreadsheet application. All formatting and styling features are best viewed in Microsoft Excel 2010+.
          </p>
        </div>
      </div>
    </div>
  );
}

export default ExcelExportDemo;
